### ISSUE TITLE
Unbinding / Canceling

### ISSUE THREAD

**Issue by TheBox193** [mrjoelkemp/jquery.bum-smack#10]
Would calling `$(this).off('scroll.smack')` externally be an acceptable way to unbind if it is no longer going to resolve? Say the div content swaps for a different view, or change pages on a single page app - the binding is no longer needed.

Is there maybe a better way to clean it up?

**Comment by pawel-piskorz** [comment]
IMO yes, calling $(this).off('scroll.smack') is a proper way to disable bum-smack for an element.

**Comment by TheBox193** [comment]
Thanks, works for me -
