### ISSUE TITLE
Allow percentage and pixel threshold smack for 'top' edge

### ISSUE THREAD

**Issue by mrjoelkemp** [mrjoelkemp/jquery.bum-smack#6]
Need to track the scroll direction to avoid the case:

> if you're at the top of the div, bind to a percentage threshold from the top, and then scroll down, you'll incorrectly trigger the smack.

**Comment by pawel-piskorz** [comment]
I am detecting direction like you suggested, seems to work fine but there is one thing:
for the following settings {edge:"top", threshold:"100px"} when scroll down less than 100px, and then scroll up, it triggers the smack. I think this is how it is suppose to work, but I would like to know your opinion.

**Comment by mrjoelkemp** [comment]
> for the following settings {edge:"top", threshold:"100px"} when scroll down less than 100px, and then scroll up, it triggers the smack. I think this is how it is suppose to work

I agree.

Thanks for the PR! Will look it over.
